### PR TITLE
Rename Go module name to 'github.com/kubeflow/mpi-operator'

### PR DESCRIPTION
**Pull request by tenzen-y**
Signed-off-by: Yuki Iwai <yuki.iwai.tz@gmail.com>

As discussed in https://github.com/kubeflow/mpi-operator/pull/502#issuecomment-1403515209, I renamed the Go module name to 'github.com/kubeflow/mpi-operator'.

### CODE REVIEW

**Review by alculquicondor — APPROVED** [review]
/lgtm

**Comment by alculquicondor** [comment]
@terrytangyuan

**Review by terrytangyuan — APPROVED** [review]
/lgtm

**Pull request merged**
