### PR TITLE
Fix additional printer columns in v1 CRD

### PR DESCRIPTION
**Pull request by andreyvelich**
`additionalPrinterColumns` should be under `.spec` in `CustomResourceDefinition`.
I also fixed `JSONPath` param name.

/cc @terrytangyuan @carmark

### CODE REVIEW

**Review by terrytangyuan — APPROVED** [review]
Others PTAL

/lgtm

**Comment by carmark** [comment]
@andreyvelich Should it be `jsonPath`?

image


Ref: https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#additional-printer-columns

**Comment by andreyvelich** [comment]
> @andreyvelich Should it be `jsonPath`?
> 
> image
> 
> Ref: https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#additional-printer-columns

I think they are using `apiextensions.k8s.io/v1` in that example, but we use `v1beta1` version. 
Here is API ref: https://github.com/kubernetes/apiextensions-apiserver/blob/master/pkg/apis/apiextensions/v1beta1/types.go#L255.

**Comment by carmark** [comment]
@andreyvelich 
Thanks.

/lgtm

**Review by carmark — APPROVED** [review]

**Review by terrytangyuan — APPROVED** [review]
/approve

**Pull request merged**
