### PR TITLE
Cleans up the unused go.sum dependencies

### PR DESCRIPTION
**Pull request by naveensrinivasan**
Cleans up the unused `go.sum` dependencies

### CODE REVIEW

**Review by terrytangyuan — COMMENTED** [review]
Could you add a check in the CI that checks the tidiness as well?

**Comment by naveensrinivasan** [comment]
> Could you add a check in the CI that checks the tidiness as well?

Can you point me to the CI? Probably that can be a separate PR.

**Comment by terrytangyuan** [comment]
The CI steps are defined here: https://github.com/kubeflow/mpi-operator/blob/master/.travis.yml

**Comment by naveensrinivasan** [comment]
@terrytangyuan I would suggest that be a separate PR.

**Review by terrytangyuan — APPROVED** [review]
Sure. We probably don't want to use Travis CI anyways and we need to switch to use GitHub Actions. 

/lgtm
/approve

**Comment by naveensrinivasan** [comment]
@terrytangyuan sounds good. I was thinking the same as to use GitHub actions compared to Travis.

**Pull request merged**
