### PR TITLE
Disable etc hosts per parameter

### PR DESCRIPTION
**Pull request by AssafKatz3**

### CODE REVIEW

**Review by gaocegege — COMMENTED** [review]
/assign @carmark

**Comment by carmark** [comment]
@AssafKatz3 Thanks for your PR, the code LGTM. However, could you please fix the CI issues?

**Review by terrytangyuan — COMMENTED** [review]
Thanks. Could you sign the CLA?

**Comment by terrytangyuan** [comment]
Closing due to inactivity.

**Pull request closed without merging**
