### PR TITLE
Add gpu resource pattern

### PR DESCRIPTION
**Pull request by xychu**
Make mpi-operator work with GPU resources that not end with `.com/gpu`.

### CODE REVIEW

**Review by gaocegege — APPROVED** [review]
LGTM

/assign @terrytangyuan @carmark

**Review by terrytangyuan — APPROVED** [review]
/approve

**Review by carmark — APPROVED** [review]

**Comment by xychu** [comment]
@carmark @terrytangyuan @gaocegege thanks for your review, tests have been adeed.

**Comment by gaocegege** [comment]
Should we merge it mannually?

**Pull request merged**
