### PR TITLE
MPI Operator: Consolidate manifests

### PR DESCRIPTION
**Pull request by yanniszark**
#### Current manifests structure

```
.
└── mpi-operator
    ├── base
    └── overlays
        └── application
```

#### Explanation

- The whole structure came from kubeflow/manifests.
- The `application` overlays contain Application CRs, which we want to move away from (https://github.com/kubeflow/manifests/issues/1715#issuecomment-779402779)

#### Recommended end state

```
.
└── mpi-operator
    ├── base
    └── overlays
        ├── kubeflow
        └── standalone
```

### CODE REVIEW

**Comment by yanniszark** [comment]
cc @kubeflow/wg-training-leads

**Review by terrytangyuan — COMMENTED** [review]
My main concern is about compatibility of installation methods that we kept changing

**Comment by yanniszark** [comment]
@terrytangyuan this is a valid concern indeed. Let me explain how I have addressed that:
- I have validated the diff of `manifests/mpi-operator/overlays/application` and `manifests/overlays/kubeflow` is the same, except some labels and the application CR.
- I have edited existing docs and scripts to account for the new location.

What do you think?

**Review by terrytangyuan — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
