### PR TITLE
use volcano scheduler

### PR DESCRIPTION
**Pull request by stpabhi**
This PR updates mpi-operator to use volcano

Signed-off-by: Abhilash Pallerlamudi <stp.abhi@gmail.com>

### CODE REVIEW

**Comment by terrytangyuan** [comment]
@stpabhi CI build failed: https://travis-ci.org/github/kubeflow/mpi-operator/builds/680464814

Not sure why the result is not showing up to block this PR. This has been the case recently.

**Comment by stpabhi** [comment]
@terrytangyuan retest doesn’t get triggered. At least I don’t see new builds in travis.

**Comment by terrytangyuan** [comment]
Travis is separate from Kubeflow's test infra so `/retest` won't work. You can find new builds here after you push a new commit: https://travis-ci.org/github/kubeflow/mpi-operator/pull_requests

**Comment by stpabhi** [comment]
@terrytangyuan ok, but it’s not a code issue. The Travis build says 

`/golangci-lint info checking GitHub for tag 'v1.22.2'
339golangci/golangci-lint crit unable to find 'v1.22.2' - use 'latest' or see https://github.com/golangci/golangci-lint/releases for details
340The command "curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.22.2" failed and exited with 1 during .`

**Comment by terrytangyuan** [comment]
You can retrigger CI by pushing an empty commits via `git commit --allow-empty -m "Trigger CI"`.

**Comment by stpabhi** [comment]
@terrytangyuan thanks, build succeeded. https://travis-ci.org/github/kubeflow/mpi-operator/builds/680744379

**Pull request merged**
