### PR TITLE
Upgrade golang and controller-gen

### PR DESCRIPTION
**Pull request by alculquicondor**
To prepare for release.

### CODE REVIEW

**Comment by tenzen-y** [comment]
@alculquicondor Could you follow this DCO step?
https://github.com/kubeflow/mpi-operator/pull/636/checks?check_run_id=23927150703

**Comment by alculquicondor** [comment]
I missed `make generate`.

Fixed.

**Comment by tenzen-y** [comment]
> I missed `make generate`.
> 
> Fixed.

@alculquicondor I guess that you missed `make crd`.

**Comment by tenzen-y** [comment]
> > I missed `make generate`.
> > Fixed.
> 
> @alculquicondor I guess that you missed `make crd`.

NVM. There are any other reasons...

**Comment by alculquicondor** [comment]
Yeah, I don't know what I missed

**Comment by tenzen-y** [comment]
> Yeah, I don't know what I missed

I found that your PR dropped some field from swagger.json.

`master` branch: https://github.com/kubeflow/mpi-operator/blob/1b33fec7e3596fb45e843d44544692e1423f7489/pkg/apis/kubeflow/v2beta1/swagger.json#L159-L161
this PR: https://github.com/alculquicondor/mpi-operator/blob/973702775818aac7452963f594b43da5e732089a/pkg/apis/kubeflow/v2beta1/swagger.json#L159-L161

@alculquicondor Did `make generate` succeed in your local?

**Comment by alculquicondor** [comment]
Something is hexed in my local repo

/close

**Pull request closed without merging**
