### PR TITLE
Preparing release of v0.3.0

### PR DESCRIPTION
**Pull request by alculquicondor**
/hold
Open questions:
- Release version: 0.3.0 or 1.0.0?
- Should we include older controllers in the image?

Changes:
- Release notes
- Update Makefile to use new version
- Extra notes for developers

### CODE REVIEW

**Comment by alculquicondor** [comment]
Should we upload the images to dockerhub first? @terrytangyuan

**Comment by alculquicondor** [comment]
cc @gaocegege @andreyvelich @ahg-g @rongou @carmark @zw0610

Anything else you would like to see before the release? See #373 for an overview of the changes included.

**Comment by alculquicondor** [comment]
cc @Jeffwan

**Comment by terrytangyuan** [comment]
> Should we upload the images to dockerhub first? @terrytangyuan

Either before or right after release is fine. Would you like to help upload the images once we release? If so, feel free to send me your DockerHub id and I’ll add you there.

**Comment by alculquicondor** [comment]
Yes, I can upload them. It's `alculquicondor` as well. I will upload once this PR is approved.

**Comment by Jeffwan** [comment]
Do you mean v0.3.0 or v3.0.0?

**Comment by zw0610** [comment]
Could we include both the v1 and v2 controller in the same image?

**Comment by Jeffwan** [comment]
> Could we include both the v1 and v2 controller in the same image?

Yeah, we did this for MXNet in the past. v1beta1 and v1 are included in the same image

**Comment by gaocegege** [comment]
> Could we include both the v1 and v2 controller in the same image?

I also vote for it.

**Comment by andreyvelich** [comment]
@alculquicondor @kubeflow/wg-training-leads Are we going to use this release in Kubeflow 1.4 ?
Currently, we are using the previous MPI Operator release: https://github.com/kubeflow/manifests/tree/master/apps/mpi-job/upstream.

**Comment by alculquicondor** [comment]
I meant `0.3.0`. However, I'm currently working fixing support for running as non-root #416. Then we should be ready to release.

I'm fine including both binaries, with v2 being the default.

When is kubeflow 1.4 releasing? I would like the v2 controller to be part of it.

**Comment by andreyvelich** [comment]
> When is kubeflow 1.4 releasing? I would like the v2 controller to be part of it.

The feature freeze stage until September 5th. The official release will be on September 27th.

cc @kubeflow/release-team

**Comment by alculquicondor** [comment]
Thoughts about the version (`0.3.0` or `1.0.0`)? @terrytangyuan @gaocegege and others?

**Comment by gaocegege** [comment]
Prefer 0.3.0 since we do not have many production use cases to illustrate it is stable. WDYT @terrytangyuan @Jeffwan

**Comment by terrytangyuan** [comment]
0.3.0 sounds better to me as well.

**Comment by alculquicondor** [comment]
/hold cancel

Excellent. Please let me know what I missed in this PR.

**Review by gaocegege — COMMENTED** [review]
LGTM

/cc @kubeflow/wg-training-leads @zw0610

**Review by terrytangyuan — APPROVED** [review]
/lgtm
/approve

**Comment by terrytangyuan** [comment]
@alculquicondor Is there anything else before I tag v0.3.0 from master branch?

**Comment by alculquicondor** [comment]
Uhm.. maybe modify the Dockerfile to include the 3 binaries? Then do the upload. Do I have permissions?

Also, can I entirely remove the v1alpha1 controller and API?

**Comment by terrytangyuan** [comment]
> Uhm.. maybe modify the Dockerfile to include the 3 binaries? Then do the upload. Do I have permissions?
Just gave you permissions.

> Also, can I entirely remove the v1alpha1 controller and API?
@kubeflow/wg-training-leads Any objections?

**Comment by alculquicondor** [comment]
I was able to upload `mpioperator/mpi-operator:0.3.0`, but I don't seem to have permissions to create new repositories (for the new samples).

I need all the repositories listed here: https://github.com/kubeflow/mpi-operator/blob/db6930dcd509b1d97a47bcccd1bcb1da5eaea712/Makefile#L102-L108

**Comment by terrytangyuan** [comment]
Just created the repos. Please try again.

**Comment by alculquicondor** [comment]
I see them, but I think I don't have permissions to upload images.

**Comment by terrytangyuan** [comment]
Sorry please try again.

**Comment by alculquicondor** [comment]
Excellent! The samples are working.

Can it set `mpioperator/mpi-operator:0.3.0` to also be `mpioperator/mpi-operator:latest`?

I fear some people that didn't set a version in their YAMLs will get the operator upgraded without the rest of the changes.

**Comment by terrytangyuan** [comment]
That's fine. Using latest tag is at their own risk anyways.

**Comment by alculquicondor** [comment]
Updated. Feel free to tag the commit in github now :)

Could we announce it kubeflow's twitter or somewhere else?

**Comment by terrytangyuan** [comment]
Thanks! Just released https://github.com/kubeflow/mpi-operator/releases/tag/v0.3.0

I am not sure what the current process is for the Kubeflow's Twitter handle but I tweeted it on my personal handle here: https://twitter.com/TerryTangYuan/status/1435345660232994817?s=20

**Pull request merged**
