### PR TITLE
update mpijob condition

### PR DESCRIPTION
**Pull request by wackxu**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/mpi-operator/120)

### CODE REVIEW

**Comment by wackxu** [comment]
@rongou @gaocegege @terrytangyuan @jlewi add update mpijob condition,  PTAL

**Comment by rongou** [comment]
Can you make sure the test passes? It's not included in the Travis CI build.

**Comment by wackxu** [comment]
> Can you make sure the test passes? It's not included in the Travis CI build.

I have test the operator in my local environment and it is OK.  I think we should merge https://github.com/kubeflow/mpi-operator/pull/118 first, I have fix some test in that pr and add more check for the code, so after https://github.com/kubeflow/mpi-operator/pull/118 get merged, I can update the UT as well.

**Pull request merged**
