### PR TITLE
Organize examples folder by api compatibility

### PR DESCRIPTION
**Pull request by ArangoGutierrez**
re organize examples folder to store demos under the compatible API, this way v1 and v2beta1 demos are clearly separated and easier to track

### CODE REVIEW

**Review by alculquicondor — COMMENTED** [review]
/lgtm

**Review by terrytangyuan — APPROVED** [review]
/approve

**Comment by terrytangyuan** [comment]
Would you like to help migrate some of the examples to https://github.com/kubeflow/training-operator/tree/master/examples/mpi as well?

**Comment by alculquicondor** [comment]
We didn't run the E2E tests did we? 🙃 

I think this PR broke them and new PRs are failing. Example #454

**Comment by alculquicondor** [comment]
@ArangoGutierrez  could you check?

**Comment by terrytangyuan** [comment]
Hmm not sure why it didn't run. @ArangoGutierrez Would you like to fix the e2e tests?

**Comment by ArangoGutierrez** [comment]
ups, checking

**Comment by ArangoGutierrez** [comment]
My bad https://github.com/kubeflow/mpi-operator/pull/455

**Pull request merged**
