### PR TITLE
Add StartTime and CompletionTime in job status

### PR DESCRIPTION
**Pull request by Jeffwan**
This is not a breaking API change. I think it should be fine to add into v1alpha1.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/mpi-operator/89)

### CODE REVIEW

**Comment by terrytangyuan** [comment]
@Jeffwan Tests need to be updated as well since additional fields are expected.

**Comment by Jeffwan** [comment]
@terrytangyuan Sure. I will add test.

**Pull request merged**
