### PR TITLE
propose elastic training with horovod with mpi-operator

### PR DESCRIPTION
**Pull request by zw0610**
Here we propose to support Elastic Horovod on MPI Operator. For more details, please refer the markdown file committed.

### CODE REVIEW

**Comment by johnugeorge** [comment]
Thanks for this.
/lgtm

**Review by terrytangyuan — APPROVED** [review]
The overall design looks great! Thanks for writing this up!

/approve
/lgtm

**Comment by gaocegege** [comment]
/lgtm

Thanks for the awesome work! 

/hold cancel

**Pull request merged**
