### PR TITLE
Update version of debian for Docker images

### PR DESCRIPTION
**Pull request by sheevy**
Bullseye -> Bookworm

### CODE REVIEW

**Comment by alculquicondor** [comment]
It looks like MPICH is failing, but others are passing.

**Comment by sheevy** [comment]
For me it was Intel which failed locally.
I've started this PR to ask if people have any hints what could be happening?

**Review by terrytangyuan — APPROVED** [review]
Thanks!

/lgtm

**Comment by alculquicondor** [comment]
Still failing... can you investigate locally?

**Comment by tenzen-y** [comment]
@sheevy Do you have any progress? We need to move this forward to update the OpenMPI version.
ref: #588

**Comment by tenzen-y** [comment]
I fixed the observed issue in https://github.com/kubeflow/mpi-operator/pull/661.
@sheevy Thank you for this contribution!

/close

**Pull request closed without merging**
