### PR TITLE
Increase the timeout for E2E tests

### PR DESCRIPTION
**Pull request by sheevy**
Similar to https://github.com/kubeflow/mpi-operator/pull/405

### CODE REVIEW

**Comment by alculquicondor** [comment]
I don't think individual tests are timing out. It's the whole suite that is timing out.
Note that the default timeout for `go test` is 10 minutes, as documented here: https://pkg.go.dev/cmd/go#hdr-Testing_flags:~:text=sequence%2C%20if%20any.-,%2Dtimeout%20d,-If%20a%20test

You need to increase it in the Makefile

**Comment by sheevy** [comment]
Thanks. I've doubled that timeout to 20 minutes

**Comment by alculquicondor** [comment]
could you squash?

**Comment by sheevy** [comment]
ok, I failed trying to squash. I'll try once again. Is there a way to cancel the tests so I don't waste resources?

**Comment by sheevy** [comment]
ok, now squashing worked as intended

**Review by tenzen-y — COMMENTED** [review]
Thanks!
/lgtm
/assign @alculquicondor

**Comment by tenzen-y** [comment]
Fix: #570

**Pull request merged**
