### PR TITLE
Adding helm chart

### PR DESCRIPTION
**Pull request by omesser**
- Related to Issue #11
- Versioned 0.0.1
- Tested and used in www.iguazio.com with mpi-operator version 0.2.0

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/mpi-operator/167)

### CODE REVIEW

**Comment by rongou** [comment]
/lgtm

LGTM to me. @terrytangyuan might want to take a look.

**Comment by omesser** [comment]
@terrytangyuan  thanks!

**Comment by supertetelman** [comment]
Is this a valid install path or should I be using kustomize? I'd rather helm over kustomize, but this being in a `hack` directory does not put me at ease.

**Pull request merged**
