### PR TITLE
Allow to change registry via a variable

### PR DESCRIPTION
**Pull request by sheevy**
quality of life improvement when testing dev images in private containter registry

### CODE REVIEW

**Comment by sheevy** [comment]
Weird to see the that one failure for 1.25.8. In my fork there was also 1 failure, but for 1.27.1.

**Review by alculquicondor — COMMENTED** [review]
/lgtm
/approve

**Comment by alculquicondor** [comment]
It looks like the failure is due to timeout.
Since you added more E2E tests, I think this is expected.
Can you increase the timeout in a separate PR?

**Comment by alculquicondor** [comment]
rebase instead of merge

**Comment by tenzen-y** [comment]
@sheevy Could you rebase this PR once more?

**Comment by sheevy** [comment]
@tenzen-y done

**Pull request merged**
