### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by xiaoyili**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/mpi-operator/163)

### CODE REVIEW

**Comment by gaocegege** [comment]
@xiaoyili Please sign the CLA and run `https://github.com/kubeflow/mpi-operator/blob/master/hack/update-codegen.sh` to regenerate the client.

**Comment by terrytangyuan** [comment]
@xiaoyili Please sign the CLA and reply as googlebot suggested. @gaocegege I don’t think he needs to run the codegen update script though. Am I missing anything here?

**Comment by gaocegege** [comment]
@terrytangyuan Please see the Travis CI logs. Or we can regenerate the clientset in another PR and rebase here.

**Comment by terrytangyuan** [comment]
I see. Yes that can be done by a separate PR. I can just manually merge here (once CLA is signed) if needed since it’s just a simple change.

**Comment by gaocegege** [comment]
@terrytangyuan If you have permission, I think we can merge it mannually.

**Comment by xiaoyili** [comment]
@googlebot I signed it!

**Comment by xiaoyili** [comment]
CLA signed, cheers!

**Pull request merged**
