### PR TITLE
Merge v2 Makefile into main one

### PR DESCRIPTION
**Pull request by alculquicondor**
This removes the need for a separate Dockerfile

### CODE REVIEW

**Review by terrytangyuan — COMMENTED** [review]
Is there anything else that can be merged into one as well to reduce maintenance efforts?

**Comment by terrytangyuan** [comment]
What's concerning is that changes won't be reflected in the fork, e.g. https://github.com/kubeflow/mpi-operator/pull/368

**Comment by alculquicondor** [comment]
I don't think we can merge anything else. #368 doesn't actually matter for the new controller (kubectl-delivery is going away)

**Review by terrytangyuan — APPROVED** [review]
Thanks!

/lgtm
/approve

**Pull request merged**
