### PR TITLE
Setting Intel MPI architectures separately

### PR DESCRIPTION
**Pull request by alculquicondor**
Intel MPI only seems to support linux/amd64 at the moment

### CODE REVIEW

**Review by tenzen-y — COMMENTED** [review]
/lgtm

Can you create an issue to keep tracking this?
Intel MPI experts may be able to help.

**Comment by alculquicondor** [comment]
I think that is beyond the scope of this repo

**Comment by tenzen-y** [comment]
> I think that is beyond the scope of this repo

Oh, yes.

```shell
1 package can be upgraded. Run 'apt list --upgradable' to see it.
N: Skipping acquire of configured file 'main/binary-arm64/Packages' as repository 'https://apt.repos.intel.com/oneapi all InRelease' doesn't support architecture 'arm64'
```

**Pull request merged**
