### PR TITLE
Fix: add ns filter to podLister

### PR DESCRIPTION
**Pull request by kuizhiqing**
This PR fix https://github.com/kubeflow/mpi-operator/issues/621.

Since the podList have no namespace filter, it may capture the pods with same name but in different ns.

### CODE REVIEW

**Comment by kuizhiqing** [comment]
merge https://github.com/kubeflow/mpi-operator/pull/623 first to solve CI issue.

**Review by alculquicondor — COMMENTED** [review]
/lgtm
/approve

**Review by tenzen-y — COMMENTED** [review]
/lgtm

**Pull request merged**
