### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by zuston**

### CODE REVIEW

**Review by gaocegege — COMMENTED** [review]
/lgtm
/approve

Thanks for your contribution! :tada: :+1:

**Comment by zw0610** [comment]
/LGTM

thank you!

**Comment by terrytangyuan** [comment]
@zw0610 You should add yourself to Kubeflow members. :-)

**Review by terrytangyuan — APPROVED** [review]
LGTM

**Comment by zw0610** [comment]
> @zw0610 You should add yourself to Kubeflow members. :-)

yep, just filed a pr https://github.com/kubeflow/internal-acls/pull/451

**Pull request merged**
