### PR TITLE
Start of the e2e work

### PR DESCRIPTION
**Pull request by NikeNano**
This PR/draft includes initial work to set up the e2e test for the mpi-operator following the |Kubeflow/testing guidelines](https://github.com/kubeflow/testing). 

Related to issue: https://github.com/kubeflow/mpi-operator/issues/233

The testing infrastructure is sett up in the following way(the most compete repo with the latest updates seems to be Kubeflow/examples which will be used for examples): 
1) Webhooks between Github and Prow which responds to GitHub events(this should be setup for all Kubeflow repos)
2) Prow jobs defined in the [prow_config.yam](https://github.com/kubeflow/examples/blob/master/prow_config.yaml) that execute Argo workflows based upon python scripts [example here](https://github.com/kubeflow/examples/blob/master/py/kubeflow/examples/create_e2e_workflow.py).
4) The logs are written back to GCP buckets from where they are snapped up by Gubernator (as I understand at least). 

The current PR includes the scripts to run test but not the actually e2e test that should/could be based upon the [tensor flow-benchmark.yaml](https://github.com/kubeflow/mpi-operator/blob/master/examples/v1/tensorflow-benchmarks.yaml)

For the tf-operator the e2e test can be found [here](https://github.com/kubeflow/tf-operator/blob/master/py/kubeflow/tf_operator/simple_tfjob_tests.py) as an example. It is built around a simple tf_job_client.py. One approach would be to follow this set up for inspiration. However it should be noted that the tf-operator repo test infra is built around ksonnet which is deprecated for pipelines(read argo workflows) written in python, info [here](https://github.com/kubeflow/testing#writing-an-argo-workflow-for-an-e2e-test). 

~~I have played around with the current code to get it up and running currently only doing linting on a K8s cluster.  I want to start with knowing that the basic infra is working and know how to rung things.  However I can't managed to run it end 2 end on my own cluster yet. Due to issues with~~ : 
- ~~NFS that needs to be configured~~
- ~~Issues with the [script](https://github.com/kubeflow/testing/blob/master/images/checkout_repos.sh) checking out the code. Might be related to that I run it on my own cluster~~. 

I will continue to use the Kubeflow infrastructure to develop this since I have issues with setting up my own and it gets picked up without being merged. 

I will continue to look in to this but would be happy for help/suggestions in order to speed up the process.

### CODE REVIEW

**Comment by NikeNano** [comment]
Ahh cool! It picks up the tests and run them :)

**Comment by NikeNano** [comment]
As discussed @terrytangyuan here are my initial work. I will continue to work on it but don't know when it will be done :(

**Comment by NikeNano** [comment]
Woho, no it runs :) I will start to work on the actual test :) @terrytangyuan

**Comment by NikeNano** [comment]
Will continue to work on the actual test now when everything around seems to work!

**Comment by terrytangyuan** [comment]
Great work! Thanks!

**Comment by NikeNano** [comment]
I hope to have something up after the weekend, have a lot at work this week.

**Comment by terrytangyuan** [comment]
Great. Please ping me again when ready for review.

**Comment by jlewi** [comment]
@NikeNano based on your comment in kubeflow/testing#656 it looks like you are using an auto-deployed cluster and following what the tests in kubeflow/examples are doing. This is fine if you aren't installing the operator itself and following what the examples do.

I don't think our auto-deployed clusters currently install the mpi-operator. So we might have to update the config to include the mpi operator if we want to use the auto-deployed clusters.

Did you consider using a notebook as both an example and as a test? e.g. you could create a dirt simple notebook like the mnist
https://github.com/kubeflow/examples/blob/master/mnist/mnist_gcp.ipynb

Which just creates an mpi-job and verifies it works. The advantage of this is that it serves both as a tutorial and the test verifies that the tutorial is working correctly.

We are in the process of adding support for Tekton to our CI system. See kubeflow/testing#622

One of the reasons we are adding support for Tekton is that hopefully it will make it easier to define and add new tests.  For example, if you look at that PR it includes a Tekton task for running a notebook. So hopefully once we get all of that merged it will be dirt simple to add new tests to run Tekton tests.

That said we could use help getting the PRs for Tekton support finished and merged. Let me know if that was something you would be interested in helping with.

The way that might work would be.

1. Create a notebook or python program to run your test.
1. Create a Tekton pipeline to run the test
1. Integrate the Tekton pipeline into Kubeflow CI.

**Comment by NikeNano** [comment]
Thanks @jlewi! I would be happy to help out with the Tekton integration. 

I think it would be great to simplify the testing setup, I have struggled a bit to understand all the piece working together currently. 

I will start with setting up a notebook and then help out with the Tekton work!

**Comment by NikeNano** [comment]
I have created a sample notebook that will act as the e2e test and can run it by running he notebook local and sending the job to the cluster. However I have some issues with the RBAC roles in order to create a mph-resource from the sa used by the notebook on the Kubeflow notebook server. I get the following error: 

```RuntimeError: Exception when calling CustomObjectsApi->create_namespaced_custom_object:         (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Audit-Id': '50308cfc-40cc-440d-b26d-662f6570b129', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'Date': 'Wed, 13 May 2020 06:00:26 GMT', 'Content-Length': '390'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"mpijobs.kubeflow.org is forbidden: User \"system:serviceaccount:kubeflow-niklas-sven-hansson:default-editor\" cannot create resource \"mpijobs\" in API group \"kubeflow.org\" in the namespace \"kubeflow-niklas-sven-hansson\"","reason":"Forbidden","details":{"group":"kubeflow.org","kind":"mpijobs"},"code":403}
```

I tried to update the roles and role bindings with out success so far. Will continue to look in to it. Do you know more about this @terrytangyuan? I have not worked with RBAC before. Thanks!

**Comment by terrytangyuan** [comment]
Currently MPI Operator's deployment yamls only contains this service account: https://github.com/kubeflow/mpi-operator/blob/master/deploy/v1/mpi-operator.yaml#L149

This account has permissions as outlined in its cluster role: https://github.com/kubeflow/mpi-operator/blob/master/deploy/v1/mpi-operator.yaml#L58

I think the notebook requires a different service account in a different namespace which does not have permission to manipulate the resources MPIJob requires. Probably need to look into how to change this or add your ServiceAccount/ClusterRole/ClusterRoleBinding. A good reference is: https://kubernetes.io/docs/reference/access-authn-authz/rbac/

**Comment by NikeNano** [comment]
> Currently MPI Operator's deployment yamls only contains this service account: https://github.com/kubeflow/mpi-operator/blob/master/deploy/v1/mpi-operator.yaml#L149
> 
> This account has permissions as outlined in its cluster role: https://github.com/kubeflow/mpi-operator/blob/master/deploy/v1/mpi-operator.yaml#L58
> 
> I think the notebook requires a different service account in a different namespace which does not have permission to manipulate the resources MPIJob requires. Probably need to look into how to change this or add your ServiceAccount/ClusterRole/ClusterRoleBinding. A good reference is: https://kubernetes.io/docs/reference/access-authn-authz/rbac/

Thanks!

**Comment by terrytangyuan** [comment]
Great to see the progress you are making! I saw that the notebook and MPIJob was successful though. Where can I see the errors you mentioned above?

**Comment by NikeNano** [comment]
> Great to see the progress you are making!  

Yeah, hard to get the time to work on it atm sadly though :( 

> Where can I see the errors you mentioned above?

I run the notebook locally connecting to kubeflow, successfully :) . However if we like to run it as a test, as jlewi  mention above, we need to make sure it also runs from the notebook server as far as I understand. Which have the issues with the permissions.  You can recreate the error by running the notebook from the kubeflow notebook service.

**Comment by NikeNano** [comment]
The auth:s are defined by clusterRole inheritance and labels to create the role `kubeflow-editor` here are some examples: https://github.com/kubeflow/manifests/tree/master/kubeflow-roles 

Are there plans to include the mpi-operator in the [kubeflow/manifests](https://github.com/kubeflow/manifests) @terrytangyuan ?

**Comment by terrytangyuan** [comment]
@NikeNano Check this out: https://github.com/kubeflow/manifests/tree/master/mpi-job/mpi-operator

**Comment by NikeNano** [comment]
Ohh missed that completely! Thanks!

**Comment by NikeNano** [comment]
FYI, will try to finish this during the weekend, have had a lot to do.

**Comment by NikeNano** [comment]
@terrytangyuan the notebook should be working now it would be great if you could review it. For running the notebook as part of the tests I will check up on the work by @jlewi in order to align with the work on using Tekton to simplify running the notebook tests. 

Would it be of interest to separate out the mpioperator client if someone else is interested in using it?

**Comment by NikeNano** [comment]
@terrytangyuan did a rerun to double check some things and the mpijob seems to get stuck when i run it in the notebook server namespace. The job seems to enter runing stage but then get stuck. Would be great if you could try the notebook out. In the mean time I will spend some time reading up on the manifests and cluster roles to futrher debugg since it seem to work on the default namespace when i do `kubectl apply ...`

**Comment by NikeNano** [comment]
The GPU seems to be stuck in warm up. For some reason this only happens when I try to deploy from the same namespace as the notebook is running in. Logs: 

```
 2020-05-31 17:21:37.950395: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1412] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_
xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodul
e=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.
I0531 17:21:58.049201 139923312584512 session_manager.py:500] Running local_init_op.
I0531 17:21:58.211051 139923312584512 session_manager.py:502] Done running local_init_op.
I0531 17:21:59.891191 139681432307520 session_manager.py:500] Running local_init_op.
I0531 17:22:00.132364 139681432307520 session_manager.py:502] Done running local_init_op.
Running warm up
Running warm up
2020-05-31 17:22:11.153520: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10.0
2020-05-31 17:22:11.318572: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10.0
2020-05-31 17:22:14.027879: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2020-05-31 17:22:15.036758: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
tensorflow-benchmarks-worker-0:15:19 [0] NCCL INFO NET/Socket : Using [0]eth0:10.36.3.3<0>
tensorflow-benchmarks-worker-0:15:19 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so).
tensorflow-benchmarks-worker-0:15:19 [0] NCCL INFO NET/IB : No device found.
NCCL version 2.4.7+cuda10.0
tensorflow-benchmarks-worker-0:15:19 [0] NCCL INFO Setting affinity for GPU 0 to 01
tensorflow-benchmarks-worker-1:15:19 [0] NCCL INFO NET/Socket : Using [0]eth0:10.36.2.3<0>
tensorflow-benchmarks-worker-1:15:19 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so).
tensorflow-benchmarks-worker-1:15:19 [0] NCCL INFO NET/IB : No device found.
tensorflow-benchmarks-worker-1:15:19 [0] NCCL INFO Setting affinity for GPU 0 to 01
```

from: 

```
PODNAME=$(kubectl get pods -l mpi_job_name=tensorflow-benchmarks,mpi_role_type=launcher -o name -n NAMESPACE )
kubectl logs -f ${PODNAME} -n NAMESPACE tensorflow-benchmarks```

**Comment by terrytangyuan** [comment]
@NikeNano Could we try just usiing CPUs?

**Comment by NikeNano** [comment]
Sure @terrrytangyuan, I actually didn’t know it worked with CPUs , :( How should I specify to use CPUs instead?

**Comment by terrytangyuan** [comment]
There's an example here: https://github.com/kubeflow/mpi-operator/blob/master/examples/horovod/tensorflow-mnist.yaml#L51

**Comment by terrytangyuan** [comment]
@NikeNano Looks like Tekton is now ready to be used for testing infra as @jlewi mentioned in https://github.com/kubeflow/testing/issues/425#issuecomment-643667244.

**Comment by NikeNano** [comment]
Thanks for the update @terrytangyuan I will make a push on this again!

**Comment by jlewi** [comment]
@NikeNano I don't think the notebook tests are full working yet. At least i ran into various issues. I might suggest using job_types to run them as postsubmits/periodics so you start getting signal but don't make them blocking presubmits just yet.

**Comment by NikeNano** [comment]
> @NikeNano I don't think the notebook tests are full working yet. At least i ran into various issues. I might suggest using job_types to run them as postsubmits/periodics so you start getting signal but don't make them blocking presubmits just yet.

I made some attempts yeasterday and I also had some issues. Thanks for the suggestion!

**Comment by terrytangyuan** [comment]
@NikeNano Nice progress here! Seems like it's working?

**Comment by NikeNano** [comment]
> @NikeNano Nice progress here! Seems like it's working?

I need to make sure the actual test works as well now, currently running a dummy notebook, but the hardest part should be done :)

**Comment by terrytangyuan** [comment]
Closing due to inactivity.

**Pull request closed without merging**
