### PR TITLE
Add tenzen-y as reviewer

### PR DESCRIPTION
**Pull request by tenzen-y**
I self-nominate as a reviewer.

- [22 merged PRs](https://github.com/kubeflow/mpi-operator/pulls?q=is%3Apr+is%3Aclosed+author%3Atenzen-y+merged%3A%3C%3D2023-02-28)

Also, I sorted the OWERS file according to alphabetic.

/assign @alculquicondor @terrytangyuan @kubeflow/wg-training-leads
/hold

### CODE REVIEW

**Comment by alculquicondor** [comment]
+1
@tenzen-y already has deep knowledge of the operator. Thanks for all your contributions so far.

**Review by terrytangyuan — APPROVED** [review]
Well deserved. Thanks!

/lgtm

**Comment by andreyvelich** [comment]
Thank you for your amazing contributions @tenzen-y!
/lgtm

**Pull request merged**
