### PR TITLE
Downgrade v2 API to v2beta1

### PR DESCRIPTION
**Pull request by alculquicondor**
Separate from the maturity of the controller, we should consider the maturity of the API.

I believe our current API has room for improvement. So I'd like to state this in the version name. This should be fine as the new API hasn't been announced as released and I would assume no one has been using it in production yet.

### CODE REVIEW

**Review by terrytangyuan — APPROVED** [review]
Thanks!

/lgtm
/approve

**Comment by alculquicondor** [comment]
I forgot to change one import alias

**Comment by alculquicondor** [comment]
not sure why coverage decreased with this. Can this be bypassed?

**Pull request merged**
