### PR TITLE
Fix the wrong build image path in Dockerfile

### PR DESCRIPTION
**Pull request by XinkaiWang515**
Fix the wrong build image path in Dockerfile.

### CODE REVIEW

**Comment by NikeNano** [comment]
I have some issues with deploying the mpi-operator today. I get the following error : 
``` Events:
  Type     Reason     Age                From                                                    Message
  ----     ------     ----               ----                                                    -------
  Normal   Scheduled  43s                default-scheduler                                       Successfully assigned mpi-operator/mpi-operator-65cb9fd6d7-h26r6 to gke-johanna-johanna-cpu-pool-v1-1a8bb31a-2s0m
  Normal   Pulling    25s (x3 over 42s)  kubelet, gke-johanna-johanna-cpu-pool-v1-1a8bb31a-2s0m  Pulling image "mpioperator/mpi-operator:latest"
  Normal   Pulled     24s (x3 over 40s)  kubelet, gke-johanna-johanna-cpu-pool-v1-1a8bb31a-2s0m  Successfully pulled image "mpioperator/mpi-operator:latest"
  Normal   Created    23s (x3 over 40s)  kubelet, gke-johanna-johanna-cpu-pool-v1-1a8bb31a-2s0m  Created container mpi-operator
  Warning  Failed     23s (x3 over 40s)  kubelet, gke-johanna-johanna-cpu-pool-v1-1a8bb31a-2s0m  Error: failed to start container "mpi-operator": Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/opt/mpi-operator.v1alpha2\": stat /opt/mpi-operator.v1alpha2: no such file or directory": unknown
  Warning  BackOff    11s (x2 over 23s)  kubelet, gke-johanna-johanna-cpu-pool-v1-1a8bb31a-2s0m  Back-off restarting failed container```

It this somehow related to this PR? The time of the rebuild seems to correlated well.

**Comment by rongou** [comment]
Yeah seems like it's copying from the wrong path. Sent fix #251

**Comment by terrytangyuan** [comment]
@NikeNano thanks for spotting this!

**Pull request merged**
