### PR TITLE
fix dockerfile copy path

### PR DESCRIPTION
**Pull request by rongou**
@terrytangyuan

### CODE REVIEW

**Comment by NikeNano** [comment]
@rongou how are the rebuild of the image triggered? Can’t see any new images and don’t understand if there is any auto builds to dockerhub.

**Comment by XinkaiWang515** [comment]
@rongou Hi, Rongou. Is the  '_output' a hidden directory? Can you explain why does this change work? Thank you so much.

**Comment by rongou** [comment]
@NikeNano it should build on dockerhub, but it might take a while.

@XinkaiWang515 the `Makefile` puts the output in `_output/cmd/bin` (see https://github.com/kubeflow/mpi-operator/blob/master/Makefile#L1).

**Comment by XinkaiWang515** [comment]
@rongou I see. Thanks for your help!

**Pull request merged**
