### PR TITLE
Stop using k8s.io/sample-controller

### PR DESCRIPTION
**Pull request by tenzen-y**
I replaced the `signals.SetupSignalHandler()` from `k8s.io/sample-controller` with `kubeapiserver.SetupSignalHandler()` from `k8s.io/apiserver/pkg/server`.

Fixes: #367

### CODE REVIEW

**Review by gaocegege — COMMENTED** [review]
LGTM

**Comment by tenzen-y** [comment]
@gaocegege @alculquicondor, can you also add a `lgtm` label to this PR?

**Comment by alculquicondor** [comment]
oops
/lgtm

**Pull request merged**
