### PR TITLE
ci: add travis manifest

### LINKED ISSUE #8: run unit tests in ci
Right now the prow config is empty. Should ask it to run the unit tests.

### PR DESCRIPTION
**Pull request by rongou**
closes #8 

/cc @yncxcw

### CODE REVIEW

**Comment by rongou** [comment]
@jlewi would this work? Do you need to enable travis for the repo?

/assign @jlewi

**Comment by ankushagarwal** [comment]
/lgtm

travis needs to be enabled. @jlewi has admin access.

**Comment by jlewi** [comment]
Travis should now be enabled
/lgtm
/approve

**Pull request merged**
